### ISSUE TITLE
#11 - 내부 데이터베이스 생성

### ISSUE THREAD

**Issue by zangsu** [zangsu/cs-test-service#11]
#11 - 내부 데이터베이스 생성

# Tasks
- [x] cs 문제 5문제 만들기
- [x] 문제 데이터베이스 생성하기
- [x] 사용자의 입력 정답을 저장하는 데이터베이스 생성하기

# Related Issues
none

# Time line
03.15 ~ 03.21

**Comment by zangsu** [comment]
3/15 : `GET /problem` 해결
+ 문제 정보를 저장할 `Problem` 클래스 구현
+ 문제를 저장할 `ProblemRepository` 생성
+ 문제 페이지에서 사용할 `ProblemController` 생성
  + `GET` 메서드에 해당하는 로직 구현

**Comment by zangsu** [comment]
3/16 : 컨트롤러 리팩토링, `POST /problem` 구현
+ `Problem` 수정 (`String correction` -> `int correction`)
+ 컨트롤러 리팩토링
  + 두 메서드에서 동일하게 존재하는 파라미터인 `problemNumber` 검증 로직을 개별 구현
+ `POST` 메서드에 동작하는 컨트롤러 로직 구현
+ `response` 작성 메서드 리팩토링
  + 두 메서드에서 반환되는 데이터 타입이 다름
  + 두 다른 모양의 데이터 타입을 한번에 `response`에 전달할 수 있도록 수정
  + `Object` 클래스로 업캐스팅
