### ISSUE TITLE
#30 - fetch URL 분기

### ISSUE THREAD

**Issue by Moon-GD** [zangsu/cs-test-service#30]
# Issue Number : #30 - fetch URL 분기

# Tasks
- [x] 개발/배포 환경 구분 함수 제작
- [x] fetch URL 분기
- [x] 환경에 맞게 fetch 요청 보내도록 로직 수정

# Related Issues

# Time line
04.05 ~ 04.07

**Comment by Moon-GD** [comment]
오프라인 미팅을 통해 함께 해결하였습니다.
