### ISSUE TITLE
#8 - 메인화면 와이어 프레임 구성

### ISSUE THREAD

**Issue by Moon-GD** [zangsu/cs-test-service#8]
# Issue Number : #8 - 메인화면 와이어 프레임 구성

# Tasks
- [x] 메인화면 레퍼런스 탐색
- [x] 메인화면 템플릿 제작
- [x] 메인화면 스타일링 적용 

# Related Issues
None

# Time line
03.14 ~ 03.15

**Comment by Moon-GD** [comment]
웹 디자인 레퍼런스
- <a href="https://www.awwwards.com/inspiration/thumbnail-submission-63efaa0f4b0b6349854870">반반 슬라이드</a>
- <a href="https://www.awwwards.com/sites/thrive-digital">귀여운 캐릭터 컨셉</a>

**Comment by Moon-GD** [comment]
메인 화면 와이어 프레임 구성 완료

https://user-images.githubusercontent.com/74173976/226090244-a08106ba-fc0e-45d6-a450-f14d1169afb2.mp4
