### ISSUE TITLE
#2 - 사용자 세션 관리

### ISSUE THREAD

**Issue by zangsu** [zangsu/cs-test-service#9]
# Issue Number : #2 - 사용자 세션 관리

# Tasks
- [x] 사용자 클래스 생성
- [x] 세션 관리 데이터베이스 생성
- [x] 세션 등록 컨트롤러 구현

# Related Issues
None

# Time line
03.14 ~ 03.15

**Comment by zangsu** [comment]
사용자 클래스 `User` 생성 완료
세션 관리 데이터베이스 `SessionRepository` 생성 완료
세션 등록 서블릿 `UserServlet` 구현 완료
 3.14 //
